Pull Request - Leandro Wanderley Couto da Silva
cesar-school/eta-unit-testing-project-2019.2-Manaus pull request #3
Opened 2020-10-14 19:23 UTC by leandrowcs

2020-11-04 05:23 UTC, miltonmc requested changes
Para recuperar a nota você precisa trabalhar nos comentários que deixei nesse PR. Nessa etapa, A nota limite será 7.

Estou recebendo as mudanças até o dia 15 de novembro.

Qualquer duvida pode perguntar no PR que eu repondo aqui mesmo.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        String date = LocalDate.now().getYear() + "-0" + nums.get(month) + "-0" +  nums.get(day);
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia, mês e ano calculado podem variar entre uma chamada e outra, o que pode provocar intermitências no resultado do teste.

**Evite usar números randômicos e basear seus testes em variáveis do sistema!**

Para isso,  use um valore imutável em `setBirthday()` e crie um [stub](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks) do método getNow() retornando uma data fixa.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        String date = LocalDate.now().getYear() + "-" + LocalDate.now().getMonthValue() + "-0" +  listNum.get(day);
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia, mês e ano calculado podem variar entre uma chamada e outra, o que pode provocar intermitências no resultado do teste.

**Evite usar números randômicos e basear seus testes em variáveis do sistema!**

Para isso,  use um valore imutável em `setBirthday()` e crie um [stub](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks) do método getNow() retornando uma data fixa.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(x.isBirthdayToday());
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia calculado pode ser diferente do calculado entre uma e outra chamada ao `getNow()`, o que pode provocar intermitências no resultado do teste.

**Evite basear seus testes em variáveis do sistema!**

Para isso,  use um valore imutável em `setBirthday()` e crie um [stub](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks) do método getNow() retornando essa mesma data.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(familyNewMember[0]);
Sempre que o método `addToFamily()` for chamado, `familyNewMember[0]`  retornará `true`. O que não significa que o método `addToFamily()` foi corretamente implementado.

**Verifique se o atributo `family` contém a pessoa adicionada**

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertEquals(x.isFamily(x1), x1.isFamily(x));
Além de criar um acoplamento com o método `isFamily()`,  essa verificação não garante a correta implementação do método `addToFamily()`.

Pois se `x.isFamily(x1)`retornar false e `x1.isFamily(x)` retornar false o teste ainda assim passará. Além disso, esse teste está depende que o cenário do teste anterior esteja corretamente implementado.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(x1.isFamily(new Person()));
Esse código está verificando de o stub de `isFamily()` retorna `false` (o que sempre ocorrerá), independente da correta implementação do método `isFamily()`.

**Não sobrescreva o método que está sendo testado!**

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        x.addToFamily(x1);
Dessa forma o teste fica acoplado ao método `addToFamily()`, o que pode resultar em um falso negativo, caso o método apresente algum problema em sua implementação.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(x2.isFamily(x));
Esse código está verificando de o stub de `isFamily()` retorna `true` (o que sempre ocorrerá), independente da correta implementação do método `isFamily()`.

**Não sobrescreva o método que está sendo testado!**

2020-11-05 21:17 UTC, leandrowcs commented
Prof. Milton,

Acabei de efetuar as correções, não sei se implementei corretamente.
Daí já commitei o código, mas não sei como resolver aqui no pull request!

2020-12-15 02:49 UTC, miltonmc approved these changes
Aprovado!

2020-12-15 02:50 UTC, closed without merging