Ketlin Pedron
cesar-school/eta-unit-testing-project-2019.2-Manaus pull request #4
Opened 2020-10-15 21:00 UTC by kpedron

Signed-off-by: Ketlin Pedron <pedron.ketlin@gmail.com>

2020-11-04 05:23 UTC, miltonmc requested changes
Para recuperar a nota você precisa trabalhar nos comentários que deixei nesse PR. Nessa etapa, A nota limite será 7.

Estou recebendo as mudanças até o dia 15 de novembro.

Qualquer duvida pode perguntar no PR que eu repondo aqui mesmo.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
O método `isBirthdayToday()` chama o `getNow()`, que chama `LocalDate.now()` e pega do sistema a data no momento em que é executado. Sendo assim, isso provocará intermitências no resultado do teste a depender de quando ele é executado.

**Evite basear seus testes em variáveis do sistema!** 

Para isso, crie um [stub](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks) para fixar a data retornada pelo método `getNow()`.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
O método `isBirthdayToday()` chama o `getNow()`, que chama `LocalDate.now()` e pega do sistema a data no momento em que é executado. Sendo assim, isso provocará intermitências no resultado do teste a depender de quando ele é executado.

**Evite basear seus testes em variáveis do sistema!** 

Para isso, crie um [stub](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks) para fixar a data retornada pelo método `getNow()`.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(person.isBirthdayToday());
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia calculado pode ser diferente do calculado entre uma e outra chamada ao `getNow()`, o que pode provocar intermitências no resultado do teste.

**Evite basear seus testes em variáveis do sistema!**

Para isso,  use um valore imutável em `setBirthday()` e crie um [stub](https://spring.io/blog/2007/01/15/unit-testing-with-stubs-and-mocks) do método getNow() retornando essa mesma data.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(member[0]);
Sempre que o método `addToFamily()` for chamado, `member[0]`  retornará `true`. O que não significa que o método `addToFamily()` foi corretamente implementado.

**Verifique se o atributo `family` contém a pessoa adicionada**

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertEquals(person.isFamily(person_new), person_new.isFamily(person));
Além de criar um acoplamento com o método `isFamily()`,  essa verificação não garante a correta implementação do método `addToFamily()`.

Pois se `person.isFamily(p1)`retornar false e `person_new.isFamily(p)` retornar false o teste ainda assim passará. Além disso, esse teste está depende que o cenário do teste anterior esteja corretamente implementado.

2020-11-04 05:23 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        person.addToFamily(new_person);
Dessa forma o teste fica acoplado ao método `addToFamily()`, o que pode resultar em um falso negativo, caso o método apresente algum problema em sua implementação.

2020-11-16 15:39 UTC, kpedron commented
Vou abrir um novo pull request, não sei como atualizar esse.

2020-12-15 02:55 UTC, miltonmc approved these changes
Aprovada!

2020-12-15 02:56 UTC, closed without merging